### ISSUE TITLE
Create Template For User Story [3]

### ISSUE THREAD

**Issue by halloweentown** [halloweentown/SOEN341-W21-A7#1]
### **Functional Requirements**
Qualitative needs specified in a non-technical manner (aka *natural language*). ex:	
- [x]  Story # Team members can add new user stories easily with a template
- [x] User stories created must have all required info
- [x] example

### **Non-Functional Requirments / Specifications**

- [x]  Naming convention present in card name
- [x] Story points displayed in card name
- [x] Ideal hours listed on tasks

### **Tasks**

- [x]  (1) Review course materials for user story definition
- [x] (1) Implement template
- [x] (0.5) Test template functionality

### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
~~- [ ] Unit tests and test procedures have all been passed and documented~~
~~- [ ] UML Diagrams updated and/or created~~
- [x] Wiki updated
- [x] End User documentation updated

**Comment by halloweentown** [comment]
This is a suggested template for User Stories
