### ISSUE TITLE
[US-11] As a user I want to be able to post a picture and have a caption to go with it so I can share my picture with others [25]

### ISSUE THREAD

**Issue by r-vaidya** [halloweentown/SOEN341-W21-A7#11]
### **Functional Requirements**
- [x] User must be able upload a picture 
- [x] User must be able to add a caption

### **Specification**
- [x] Must accept .jpeg file
- [x] Must accept a minimum of 140 characters
- [x] must accept file size of < 20 mB

### **Sub-User Stories**
Break down of tasks required to complete this Feature.
- [x] (7) [Create a button to post images from](https://github.com/halloweentown/SOEN341-W21-A7/projects/1#card-54419335)
- [x] (3) [Upload an image](https://github.com/halloweentown/SOEN341-W21-A7/projects/1#card-54419335)
- [x] (2) [add a caption to the image posted](https://github.com/halloweentown/SOEN341-W21-A7/projects/1#card-54889472)
- [x] (11) [I would like to have a user page to view post](https://github.com/halloweentown/SOEN341-W21-A7/projects/1#card-54889470)

### **Priority**
- [x] high

### **Acceptance Criteria**
- [x] Have an upload button on the page
- [x] Allow images from the desktop to be selected and uploaded to the site
- [x] Be able to add a caption to accompany the image
- [x] Posted image and caption should be visible on the home page

### **Risk**
- High

**Comment by CSman22** [comment]
I changed the non-function requirement to specifications
