### ISSUE TITLE
[US-13] As a User I want to follow another user so that I can view future posts from that user [7]

### ISSUE THREAD

**Issue by j-loy** [halloweentown/SOEN341-W21-A7#13]
Users shall be able to follow people that they like by clicking a button 

### **Functional Requirements**
- [x] Be able to follow another user 
- [x] able to view their future posts

### **Specifications**
Quantitative PASS/FAIL performance metrics that must be met by the implementation. ex:
- [x] Visual indicator that you are following the user
- [x] Content from followed users appears for currently logged in user

### **Tasks**
- [x] Create user profile pages 
- [x] Create a button which allows you to follow another user
- [x] Save in the database who the user is following
- [x] Save in database who have followed you 

### **Acceptance Criteria**

1.  When the user has an account and wants to follow another user 
2. Then the user should be able to click a follow button and update their database

**Comment by CSman22** [comment]
I changed Non-Functional Requirments / Specifications to just specification

**Comment by maherysm** [comment]
Removing checkboxes for Priority in the description
Adding _High Priority_ label instead
