### ISSUE TITLE
[US-14] As a User, I want to leave a comment for a picture that was posted so I can be engaged with the context of the post [9]

### ISSUE THREAD

**Issue by CSman22** [halloweentown/SOEN341-W21-A7#14]
### **Functional Requirements**
- [x] User can add a comment to photos others have posted
- [x] User is able to reply to another comment. I.e. Create one subsection of a comment

### **Specifications**
Quantitative PASS/FAIL performance metrics that must be met by the implementation. ex:
- [x] Text entry must accept a maximum of 300 characters
- [x] Able to comment that can be viewed by others
- [ ] Comments posted must appear within 30 seconds

Potential future features:
- Able to reply to comment
- Replies can be opened or closed 

### **Sub-User Stories**
Break down of tasks required to complete this Feature.
- [x] (5) [Create a comment section next to the post](https://github.com/halloweentown/SOEN341-W21-A7/projects/1#card-54419902)
- [x] (2) [Have a textbox to allow the user to write a comment](https://github.com/halloweentown/SOEN341-W21-A7/projects/1#card-54419353)
- [x] (3) [Create a database to store all comments](https://github.com/halloweentown/SOEN341-W21-A7/projects/1#card-54296486)

### **Tasks**
Break down of tasks required to complete this Feature.
- [x] Create a page next to shared content 
- [x] Create a textbox to allow the user to comment on the content 
- [x] Create a button to allow the user to reply to a comment 
- [x] Create a button to allow the user to view and close replies 
- [x] Create a database to store all the comment 

### **Acceptance Criteria**
- [x] Posted image should have a designated text box to allow comments to be added to it
- [x] Comments should be added to database and linked to the corresponding post
- [x] Comments are permanently added below the post 
- [x] There can be multiple comments to a single post

**Comment by maherysm** [comment]
Removing Risk and Medium section in comments
Adding RIsk and Medium labels instead
