### ISSUE TITLE
[US-19] Wireframe UI: As a typical user I want an intuitive user interface to be able to easily upload my content [3]

### ISSUE THREAD

**Issue by halloweentown** [halloweentown/SOEN341-W21-A7#19]
### **Functional Requirements**

- [x] User can navigate using one hand 
- [x] User can easily navigate wireframe

### **Non-Functional Requirments / Specifications**

- [x] UI never has more than 3 levels of depth from home page
- [x] User can navgiate UI using only one hand/the mouse

### **Tasks**

- [x] (.5) wireframe tool selection 
- [x] (1) analyze competition wireframes
- [x] (2) design wireframe

### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
- [x] UML Diagrams updated and/or created
- [x] Wiki updated
