### ISSUE TITLE
[US-11-2] As a user, I would like to upload image[8]

### ISSUE THREAD

**Issue by giroux2000** [halloweentown/SOEN341-W21-A7#26]
### **Specification**
- [x]  The image should be connected to the user 
- [x] Shared content needs to be made visible on User Page
- [x] Uploaded content needs to be made visible to other users
- [x] Allow sharing of only ".jpeg" and "png" file

### **Task**
- [x] connect upload button to user database 
- [x] Save image to the database

### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
- [x] Choose file button allows you to select an image file from desktop to upload
- [x] Upload button posts this image on the dashboard
- [x] The image is also added to the database
- [x] The page is refreshed once the upload button is clicked
- [x] Uploaded content is made visible to other users

### **Risk**
- High
