### ISSUE TITLE
[US-11-4] As a user, I want to have a page to view posts uploaded to the app[13]

### ISSUE THREAD

**Issue by giroux2000** [halloweentown/SOEN341-W21-A7#27]
Creating an organized page to see the uploaded image from the user 

### **Specification**
- [x] Acces database to retrieve posts from different users. 
- [x] Components Include posts, captions

### **Task**
- [x] Create a UI for the components required 

 ### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
- [x] Home page created
- [x] Displays all images that have been posted by users with comments

### **Risk**
- High
