### ISSUE TITLE
[US-11-3] As a user, I want to add a caption to my images [2]

### ISSUE THREAD

**Issue by giroux2000** [halloweentown/SOEN341-W21-A7#28]
When uploading an image there needs to be an option for adding a caption. This will allow the user to describe the image to their followers.

### **Specification**
- [x] The caption should have a word limit 250.
- [x] Only allow basic characters
- [x] The caption should appear under the photo after it is posted.

### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
- [x] While on the image upload section, an added text box is available to type in image caption
- [x] Once image has been posted, the caption is also posted underneath the image
- [x] The caption Is also linked to the database 

### **Task**
- [x] Create a textbox under uploading images
