### ISSUE TITLE
[US-11-1] As a user I would like to see a button to post images [5]

### ISSUE THREAD

**Issue by r-vaidya** [halloweentown/SOEN341-W21-A7#33]
### **Reqs**
- [x] Upload button needs to be made visible to the user indicating to upload a post
- [x] Clicking the upload button should create a popup to indicate the user to upload an image and a caption 

### **Tasks**
- [x] Create a button to post
- [x] create a popup/fragment to upload the image and caption 

### **Risk**
- Low

### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
- [ ] Unit tests and test procedures have all been passed and documented
- [ ] UML Diagrams updated and/or created
- [ ] Wiki updated
- [ ] End User documentation updated
- [ ] Clicking the button should refresh the page
- [ ] Does not allow to post a picture when the picture is not selected

**Comment by halloweentown** [comment]
React front end button needs to be Dev'd.
Back end functional using .PHP files
