### ISSUE TITLE
[US-17] As a User I want to have a login page so that I can access my account with my credentials (8) 

### ISSUE THREAD

**Issue by j-loy** [halloweentown/SOEN341-W21-A7#46]
### **Functional Requirements**
- [x]  Allow user to access profile with their credentials
- [x]  Check database if account exist
- [x] Direct user to their profile after login

### **Specifications**
- [x] Able to determine if account account exist
- [x] Check if password matches username if exist
- [x] Direct to profile in less than 30 seconds

### **Tasks**

- [x] Create page for login page
- [x] Set up Login button, and text field 
- [x] Create Database for accounts

### **Acceptance Criteria**
Card can be marked as 'Done' when the following have been completed:
- [x] Before accessing the homepage, there is a page to login or register
- [x] Entering the correct login ID and corresponding password(which is stored and checked from within the database) allows you to access the homepage of the website.
- [x] Error is displayed when the wrong login ID and/or password is typed in
- [x] Unit tests and test procedures have all been passed and documented
- [x] UML Diagrams updated and/or created
- [x] Wiki updated
- [x] End User documentation updated
