### ISSUE TITLE
[US-16] As a user I want to have a User Profile page so that I can see my posts and also my "Followers" and who I "Follow" [9]

### ISSUE THREAD

**Issue by halloweentown** [halloweentown/SOEN341-W21-A7#69]
As a user, I shall be able to see what I have posted before and be able to see a list of whom I am following and who is following me.  

### **Functional Requirements**

- [x] Another page for the profile 
- [x] The profile page should only include the post that the user has posted 
- [x] The profile page should display a list of who is following and who is following the user. 

### **Specifications**

- [x] Retrieve user post in the database within 2 seconds when refreshing the page 
- [x] Retrieve who is following the user from the database within 3 seconds when refreshing the page
- [x] Retrieve Who the user is following from the database within 3 seconds when refreshing the page 

### **Acceptance Criteria**

- [x] Clicking on your username will redirect you to your profile page
- [x] Profile page will pull all posts made by the user from the database and display it on the webpage
- [x] Have a separate webpage to display information regarding "Followers"
- [x] This webpage should be split into 2 halves, one displaying "Followers" and the other showing "Following"
- [x] "Followers" would display all other users that are following the logged in user 
- [x] "Following" would display all the users that the logged in user is following.
