### ISSUE TITLE
[SAT-01] Set up Enlightn and discuss 10 problems in the report [4]

### ISSUE THREAD

**Issue by CSman22** [halloweentown/SOEN341-W21-A7#81]
### **Tasks**

- [x]  Set up Enlightn 
- [x]  Learn how to run the tool and explain in report 
- [x] Write about the 10 detected problems
